/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRepoRouteImport } from './routes/$username.$repo'
import { Route as UsernameRepoIndexRouteImport } from './routes/$username.$repo.index'
import { Route as UsernameRepoCommitsRouteImport } from './routes/$username.$repo.commits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRepoRoute = UsernameRepoRouteImport.update({
  id: '/$username/$repo',
  path: '/$username/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRepoIndexRoute = UsernameRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsernameRepoRoute,
} as any)
const UsernameRepoCommitsRoute = UsernameRepoCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => UsernameRepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username/$repo': typeof UsernameRepoRouteWithChildren
  '/$username/$repo/commits': typeof UsernameRepoCommitsRoute
  '/$username/$repo/': typeof UsernameRepoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username/$repo/commits': typeof UsernameRepoCommitsRoute
  '/$username/$repo': typeof UsernameRepoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username/$repo': typeof UsernameRepoRouteWithChildren
  '/$username/$repo/commits': typeof UsernameRepoCommitsRoute
  '/$username/$repo/': typeof UsernameRepoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/$username/$repo' | '/$username/$repo/commits' | '/$username/$repo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$username/$repo/commits' | '/$username/$repo'
  id:
    | '__root__'
    | '/'
    | '/$username/$repo'
    | '/$username/$repo/commits'
    | '/$username/$repo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRepoRoute: typeof UsernameRepoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$repo': {
      id: '/$username/$repo'
      path: '/$username/$repo'
      fullPath: '/$username/$repo'
      preLoaderRoute: typeof UsernameRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$repo/': {
      id: '/$username/$repo/'
      path: '/'
      fullPath: '/$username/$repo/'
      preLoaderRoute: typeof UsernameRepoIndexRouteImport
      parentRoute: typeof UsernameRepoRoute
    }
    '/$username/$repo/commits': {
      id: '/$username/$repo/commits'
      path: '/commits'
      fullPath: '/$username/$repo/commits'
      preLoaderRoute: typeof UsernameRepoCommitsRouteImport
      parentRoute: typeof UsernameRepoRoute
    }
  }
}

interface UsernameRepoRouteChildren {
  UsernameRepoCommitsRoute: typeof UsernameRepoCommitsRoute
  UsernameRepoIndexRoute: typeof UsernameRepoIndexRoute
}

const UsernameRepoRouteChildren: UsernameRepoRouteChildren = {
  UsernameRepoCommitsRoute: UsernameRepoCommitsRoute,
  UsernameRepoIndexRoute: UsernameRepoIndexRoute,
}

const UsernameRepoRouteWithChildren = UsernameRepoRoute._addFileChildren(
  UsernameRepoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRepoRoute: UsernameRepoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
